import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Apple, ArrowRight, Bike, BrainCircuit, Check, ChevronRight, Clock3, Dumbbell, Flame, Footprints, HeartPulse, LogOut, Menu, Moon, Play, Plus, ShieldCheck, Sparkles, Sun, Target, TrendingUp, UserRound, Waves, X, Zap} from 'lucide-react';
import {Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import './styles.css';

const API = (import.meta.env.VITE_API_BASE_URL || 'https://fitness-mono-bs2k.onrender.com').replace(/\/$/, '');
const activityTypes = ['RUNNING','WALKING','CYCLING','SWIMMING','WEIGHT_TRAINING','YOGA','HIIT','CARDIO','STRETCHING','OTHER'];
const icons={RUNNING:Footprints,WALKING:Footprints,CYCLING:Bike,SWIMMING:Waves,WEIGHT_TRAINING:Dumbbell,YOGA:HeartPulse,HIIT:Zap,CARDIO:HeartPulse,STRETCHING:Activity,OTHER:Activity};

async function request(path, {token, method='GET', body, headers={}}={}){
  const res=await fetch(`${API}${path}`,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...headers},body:body?JSON.stringify(body):undefined});
  const text=await res.text(); let data; try{data=text?JSON.parse(text):null}catch{data=text}
  if(!res.ok) throw new Error(typeof data==='string'?data:(data?.message||'Request failed'));
  return data;
}
const fmtType=s=>s?.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())||'Activity';
const fmtDate=d=>d?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(d)):'Just now';
const day=d=>new Intl.DateTimeFormat('en',{weekday:'short'}).format(new Date(d));

function App(){
 const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('pulsefit_session'))}catch{return null}});
 const [dark,setDark]=useState(()=>localStorage.getItem('pulsefit_theme')==='dark');
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('pulsefit_theme',dark?'dark':'light')},[dark]);
 const saveSession=s=>{setSession(s); localStorage.setItem('pulsefit_session',JSON.stringify(s))};
 if(!session) return <Auth onAuth={saveSession} dark={dark} setDark={setDark}/>;
 return <Dashboard session={session} logout={()=>{localStorage.removeItem('pulsefit_session');setSession(null)}} dark={dark} setDark={setDark}/>;
}

function Auth({onAuth,dark,setDark}){
 const [mode,setMode]=useState('login'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);try{
   if(mode==='register'){const user=await request('/api/auth/register',{method:'POST',body:{firstname:f.get('firstname'),lastname:f.get('lastname'),email:f.get('email'),password:f.get('password'),role:'USER'}}); const login=await request('/api/auth/signin',{method:'POST',body:{email:f.get('email'),password:f.get('password')}}); onAuth(login)}
   else onAuth(await request('/api/auth/signin',{method:'POST',body:{email:f.get('email'),password:f.get('password')}}));
 }catch(err){setError(err.message)}finally{setLoading(false)}};
 return <main className="auth-shell"><button className="theme-fab" onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><section className="auth-copy"><div className="brand"><span className="brand-mark"><Zap size={19}/></span><b>PulseFit</b></div><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> YOUR FITNESS, INTELLIGENTLY</span><h1>Train with purpose.<br/><i>Feel the progress.</i></h1><p>A focused fitness command center built around your activities, performance, and smarter recommendations.</p><div className="proof"><span><Check size={16}/> Track every session</span><span><Check size={16}/> See your momentum</span><span><Check size={16}/> Get recommendations</span></div></div><div className="floating-stat one"><Flame size={18}/><b>482</b><small>kcal today</small></div><div className="floating-stat two"><TrendingUp size={18}/><b>+18%</b><small>this week</small></div></section>
 <section className="auth-panel"><div className="auth-card"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><h2>{mode==='login'?'Welcome back':'Start your journey'}</h2><p>{mode==='login'?'Your next milestone is waiting.':'Create an account and start tracking.'}</p><form onSubmit={submit}>{mode==='register'&&<div className="name-row"><label>First name<input name="firstname" required placeholder="Aryan"/></label><label>Last name<input name="lastname" required placeholder="Mishra"/></label></div>}<label>Email<input type="email" name="email" required placeholder="you@example.com"/></label><label>Password<input type="password" name="password" required minLength="4" placeholder="••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Please wait...':mode==='login'?'Enter dashboard':'Create account'}<ArrowRight size={18}/></button></form><div className="api-note"><span></span> Connected to your Fitness Monolith API</div></div></section></main>
}

function Dashboard({session,logout,dark,setDark}){
 const user=session.user; const [activities,setActivities]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showLog,setShowLog]=useState(false),[showRec,setShowRec]=useState(false),[selected,setSelected]=useState(null),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const a=await request('/api/activities',{token:session.token,headers:{'X-User-ID':user.id}});setActivities(Array.isArray(a)?a:[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const today=new Date().toDateString();const todays=activities.filter(a=>a.startTime&&new Date(a.startTime).toDateString()===today);return {sessions:todays.length||activities.length,cal:activities.reduce((s,a)=>s+(Number(a.caloriesBurned)||0),0),mins:activities.reduce((s,a)=>s+(Number(a.duration)||0),0),streak:activities.length?Math.min(activities.length,7):0}},[activities]);
 const chart=useMemo(()=>{const map={};activities.forEach(a=>{const k=a.startTime?day(a.startTime):'Today';map[k]=(map[k]||0)+(Number(a.caloriesBurned)||0)});return Object.entries(map).slice(-7).map(([name,calories])=>({name,calories}))},[activities]);
 const latest=[...activities].sort((a,b)=>new Date(b.startTime||0)-new Date(a.startTime||0)).slice(0,5);
 const saveActivity=async payload=>{try{const created=await request('/api/activities',{token:session.token,method:'POST',body:{...payload,userId:user.id}});setActivities(x=>[created,...x]);setShowLog(false);flash('Activity saved — keep going!')}catch(e){flash(e.message,true)}};
 const flash=(msg,bad=false)=>{setToast((bad?'⚠ ':'✓ ')+msg);setTimeout(()=>setToast(''),3500)};
 return <div className="app-shell"><aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><span className="brand-mark"><Zap size={19}/></span><b>PulseFit</b></div><nav><a className="nav-active"><Activity size={19}/>Overview</a><a onClick={()=>setShowLog(true)}><Plus size={19}/>Log activity</a><a onClick={()=>setShowRec(true)}><BrainCircuit size={19}/>Recommendations</a></nav><div className="sidebar-bottom"><div className="user-mini"><span>{(user.firstname?.[0]||'U').toUpperCase()}</span><div><b>{user.firstname||'Athlete'} {user.lastname||''}</b><small>{user.email}</small></div></div><button onClick={logout}><LogOut size={18}/>Sign out</button></div></aside><div className="content"><header><button className="menu-btn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><span className="eyebrow">THURSDAY, AUG 27</span><h1>Good afternoon, {user.firstname||'Athlete'} <span>✦</span></h1></div><div className="header-actions"><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="primary" onClick={()=>setShowLog(true)}><Plus size={18}/>Log activity</button></div></header>
 {toast&&<div className="toast">{toast}</div>}{error&&<div className="api-error">Could not load activities: {error}<button onClick={load}>Try again</button></div>}
 <section className="stats-grid"><Stat icon={<Flame/>} label="Total calories" value={stats.cal.toLocaleString()} suffix="kcal" trend="All tracked sessions"/><Stat icon={<Clock3/>} label="Training time" value={stats.mins} suffix="min" trend="Total active minutes"/><Stat icon={<Target/>} label="Activities" value={activities.length} suffix="logged" trend="Every workout counts"/><Stat icon={<Zap/>} label="Current streak" value={stats.streak} suffix="days" trend={stats.streak?'Keep the rhythm alive':'Log today to start'}/></section>
 <section className="dashboard-grid"><div className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">PERFORMANCE</span><h2>Calorie momentum</h2></div><span className="pill">Last sessions</span></div><div className="chart-wrap">{chart.length?<ResponsiveContainer width="100%" height={260}><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity=".35"/><stop offset="100%" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="calories" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer>:<EmptyChart/>}</div></div>
 <div className="panel goal-panel"><span className="eyebrow">TODAY'S FOCUS</span><h2>Make it count.</h2><p>One focused session can change the direction of your whole day.</p><div className="goal-ring"><div><b>{Math.min(100,Math.round(stats.mins/60*100))}%</b><small>60 min goal</small></div></div><button className="secondary wide" onClick={()=>setShowLog(true)}>Start logging <ChevronRight size={17}/></button></div></section>
 <section className="bottom-grid"><div className="panel recent-panel"><div className="panel-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Your latest sessions</h2></div><button className="text-btn" onClick={load}>Refresh</button></div>{loading?<div className="loading">Loading your fitness data…</div>:latest.length?latest.map(a=><ActivityRow key={a.id} a={a} onClick={()=>{setSelected(a);setShowRec(true)}}/>):<div className="empty-state"><Dumbbell size={28}/><h3>No workouts yet</h3><p>Log your first activity and start building momentum.</p><button className="primary" onClick={()=>setShowLog(true)}>Log first activity</button></div>}</div><div className="panel insight-panel"><div className="insight-icon"><BrainCircuit size={23}/></div><span className="eyebrow">SMART INSIGHT</span><h2>Ready for a recommendation?</h2><p>Select one of your activities and save personalized suggestions, improvements, and safety notes directly to your API.</p><button className="primary wide" onClick={()=>setShowRec(true)}>Open recommendations <ArrowRight size={17}/></button></div></section></div>{showLog&&<ActivityModal onClose={()=>setShowLog(false)} onSave={saveActivity}/>} {showRec&&<RecommendationModal session={session} user={user} activities={activities} selected={selected} onClose={()=>{setShowRec(false);setSelected(null)}} flash={flash}/>}</div>
}
function Stat({icon,label,value,suffix,trend}){return <div className="stat-card"><div className="stat-icon">{icon}</div><span>{label}</span><h2>{value} <small>{suffix}</small></h2><p><TrendingUp size={14}/>{trend}</p></div>}
function ActivityRow({a,onClick}){const Icon=icons[a.type]||Activity;return <button className="activity-row" onClick={onClick}><span className="activity-icon"><Icon size={20}/></span><div className="activity-info"><b>{fmtType(a.type)}</b><small>{fmtDate(a.startTime)}</small></div><div className="activity-meta"><b>{a.caloriesBurned||0} <small>kcal</small></b><span>{a.duration||0} min</span></div><ChevronRight size={18}/></button>}
function EmptyChart(){return <div className="empty-chart"><BarChart3/><p>Your chart will come alive after you log activities.</p></div>}
function ActivityModal({onClose,onSave}){const [type,setType]=useState('RUNNING'),[saving,setSaving]=useState(false);const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);onSave({type,duration:Number(f.get('duration')),caloriesBurned:Number(f.get('calories')),startTime:new Date(f.get('startTime')).toISOString(),additionalMetrics:{notes:f.get('notes')||'',distance:f.get('distance')?Number(f.get('distance')):null}}).finally?.(()=>setSaving(false))};return <Modal title="Log an activity" subtitle="Capture the work. Build the habit." onClose={onClose}><form className="modal-form" onSubmit={submit}><div className="type-grid">{activityTypes.map(t=>{const I=icons[t];return <button type="button" key={t} className={type===t?'selected':''} onClick={()=>setType(t)}><I size={18}/>{fmtType(t)}</button>})}</div><div className="form-grid"><label>Duration (minutes)<input required name="duration" type="number" min="1" placeholder="45"/></label><label>Calories burned<input required name="calories" type="number" min="0" placeholder="420"/></label><label>Start time<input required name="startTime" type="datetime-local" defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></label><label>Distance (optional)<input name="distance" type="number" step="0.1" placeholder="5.2"/></label></div><label>Notes<input name="notes" placeholder="How did it feel?"/></label><button className="primary wide" disabled={saving}>{saving?'Saving…':'Save activity'}<ArrowRight size={18}/></button></form></Modal>}
function RecommendationModal({session,user,activities,selected,onClose,flash}){const [activityId,setActivityId]=useState(selected?.id||activities[0]?.id||''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('');const selectedActivity=activities.find(a=>a.id===activityId);const load=async()=>{if(!activityId)return;setLoading(true);setError('');try{setItems(await request(`/api/recommendation/activity/${activityId}`,{token:session.token}))}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{if(activityId)load()},[activityId]);const save=async e=>{e.preventDefault();if(!activityId)return setError('Choose an activity first.');const f=new FormData(e.currentTarget);const split=n=>(f.get(n)||'').split('\n').map(x=>x.trim()).filter(Boolean);try{await request('/api/recommendation/generate',{token:session.token,method:'POST',body:{userId:user.id,ActivityId:activityId,suggestion:split('suggestion'),improvements:split('improvements'),safety:split('safety')}});flash('Recommendation saved successfully');load();e.currentTarget.reset()}catch(e){setError(e.message)}};return <Modal title="Recommendations" subtitle="Attach useful coaching notes to a specific workout." onClose={onClose}><div className="recommendation-top"><label>Activity<select value={activityId} onChange={e=>setActivityId(e.target.value)}><option value="">Choose an activity</option>{activities.map(a=><option key={a.id} value={a.id}>{fmtType(a.type)} · {fmtDate(a.startTime)}</option>)}</select></label>{selectedActivity&&<div className="selected-workout"><Flame size={17}/>{fmtType(selectedActivity.type)} · {selectedActivity.duration} min · {selectedActivity.caloriesBurned} kcal</div>}</div>{!activities.length?<div className="empty-state compact"><Dumbbell/><p>Log an activity before adding recommendations.</p></div>:<><form className="modal-form rec-form" onSubmit={save}><label>Suggestions <textarea name="suggestion" placeholder={'Hydrate before the session\nKeep a steady pace'}/></label><label>Improvements <textarea name="improvements" placeholder={'Add a longer warm-up\nIncrease intensity gradually'}/></label><label>Safety notes <textarea name="safety" placeholder={'Stop if you feel sharp pain\nCool down for 5 minutes'}/></label><button className="primary wide">Save recommendation <ShieldCheck size={18}/></button></form>{error&&<div className="error">{error}</div>}<div className="saved-recs"><h3>Saved for this activity</h3>{loading?<div className="loading">Loading…</div>:items.length?items.map((r,i)=><div className="saved-rec" key={r.id||i}><b>Recommendation #{i+1}</b>{[['Suggestions',r.suggestion],['Improvements',r.improvements],['Safety',r.safety]].map(([name,list])=><div key={name}><span>{name}</span>{Array.isArray(list)&&list.map(x=><p key={x}>✓ {x}</p>)}</div>)}</div>):<p className="muted">No recommendations saved yet.</p>}</div></>}</Modal>}
function Modal({title,subtitle,onClose,children}){return <div className="modal-backdrop"><div className="modal"><button className="close-btn" onClick={onClose}><X/></button><div className="modal-head"><span className="eyebrow">PULSEFIT</span><h2>{title}</h2><p>{subtitle}</p></div>{children}</div></div>}
function BarChart3(){return <TrendingUp size={32}/>}
createRoot(document.getElementById('root')).render(<App/>);
